### PR TITLE
fix search by uuid url 

### LINKED ISSUE #17: search by uuid sometimes does not return existing content

### PR DESCRIPTION
**Pull request by kflemin**
Fixes #17

### CODE REVIEW

File: lib/bcl/component_methods.rb [hunk 1]
```diff
@@ -432,7 +432,7 @@ def update_contents(array_of_tarball_components, skip_files_with_receipts)
     end
 
     def search_by_uuid(uuid, vid = nil)
-      full_url = '/api/search/*.json'
+      full_url = '/api/search.json'
```
Comment (nllong) [inline lib/bcl/component_methods.rb:435]: this is a strange fix. Glad you found it!
